### ISSUE TITLE
dig.ccMixter Internal Server Error Issue

### ISSUE THREAD

**Issue by emilysnowflake** [ArtisTechMedia/ccMixterHost#12]
When trying to load this page, the pages just hangs with "Loading". When I try to refresh the page, the error below appears: http://dig.ccmixter.org/free

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u3 Server at dig.ccmixter.org Port 80

**Comment by victor-stone** [comment]
fixed

**Comment by emilysnowflake** [comment]
All seems good now :)
