### ISSUE TITLE
TuneTrack Licensing Button

### ISSUE THREAD

**Issue by jlbrock44** [ArtisTechMedia/ccMixterHost#21]
Specific Issue:
The Licensing link from the splash page goes to:
http://tunetrack.net/  which leaves the visitor guessing about what to do next, yes?

I think the link should be:
http://tunetrack.net/artistech/pages/licensing/  (and that page needs a major redesign)
 

Larger Issue Notes:
I hacked a fix of what I thought would be easier for folks trying to license spinningmerkaba tracks.  Again it's rough but you might find it useful for a starting platform for overall cc+ licensing menu.  
http://tunetrack.net/jason-brock/pages/spinningmerkaba-licensing/

Also, The licensing image needs to be more prominent in all locations that lead to the tunetrack licensing matrix. 

![tunetrack_ccplus_icon](https://cloud.githubusercontent.com/assets/11033077/6216788/fd886368-b5c1-11e4-89e2-e789091b9a9f.png)

imho-the tunetrack licensing UI is horribly confusing and full of hurdles to purchase licenses.  This is not a ccmixter issue necessarily, but the licensing bridge from ccmixter to tunetrack should be smoothed out.

**Comment by victor-stone** [comment]
If you mean the 'Get Started' link under TuneTrack it goes to the page you recommend now.

Otherwise, the rest of this is really for tunetrack and not this (ccmixter/cchost) codebase so I'm closing this.

**Comment by jlbrock44** [comment]
Thanks Victor-

Yes, that's what I meant.  Closed issue.
