### ISSUE TITLE
Admin process error

### ISSUE THREAD

**Issue by daniloprates** [ArtisTechMedia/ccMixterHost#31]
I couldn't find the `ccadmin` folder. 
Heading to `.../admin` displays this message:

```
Fatal error: Uncaught Error: Call to undefined function split() in 
/Users/cin_dprates/dev/ccMixterHost/admin/index.php:68 Stack trace: #0 
/Users/cin_dprates/dev/ccMixterHost/admin/index.php(62): step_1() #1 {main} thrown in 
/Users/cin_dprates/dev/ccMixterHost/admin/index.php on line 68
```

**Comment by victor-stone** [comment]
so the unfortunate truth is: we just don't support new installs of ccMixterHost. The code is maintained for existing installations (esp *.ccmixter.org) - I will edit the readme (after Nov. 9th) to reflect this. Really sorry about that!

**Comment by daniloprates** [comment]
No worries. I was trying to find a way to access ccMixter at work, due to that access problem. It turns out it's a DNS issue on their firewall. The support is trying to fix it.

Meanwhile I've managed to create a tiny [Node.js API mirror](https://ccm-api-mirror.herokuapp.com/?query=daniloprates&limit=50), so I might be able to dive into the stems and pells tomorrow :)

thanks,
dan
