### ISSUE TITLE
Some Content Pages broken

### ISSUE THREAD

**Issue by emilysnowflake** [ArtisTechMedia/ccMixterHost#7]
Content Pages error "Can't find xxxx template"

http://ccmixter.org/keep-ccmixter-open-and-free

http://ccmixter.org/ccmixter-big-summer-music-fest

(we have links to these pages on the homepage)

**Comment by victor-stone** [comment]
There were 11 files/pages missing but they should there now. I'm now looking into missing images

**Comment by victor-stone** [comment]
images are up to date

**Comment by emilysnowflake** [comment]
Looks great :)
